[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0-rc0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
# Internal crates
scorarium = { path = "crates/scorarium" }
scorarium-tests = { path = "crates/scorarium-tests" }

# External crates
argon2 = "0.6.0"
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["cookie"] }
axum-test = "21.1.0"
clap = { version = "4.6.6", features = ["derive", "env"] }
color-eyre = "0.6.5"
cookie = "0.18.1"
getrandom = "0.4.3"
html-escape = "0.2.15"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "sqlite", "macros", "migrate"] }
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "signal"] }
tower-http = { version = "0.7.0", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
