networks:
    nginx_proxy:
        # This is a Docker network created by whatever is running the nginx-proxy container.
        external: true

services:
    scorarium:
        image: ghcr.io/notgnoshi/scorarium:latest
        restart: unless-stopped
        networks:
            - nginx_proxy
        volumes:
            # The scorarium image is a scratch image, and doesn't have a shell to create and chown
            # this directory itself, so the user must create it themselves.
            - type: bind
              source: ./data
              target: /data
              bind:
                  create_host_path: false
        command: ["--demo"]  # Remove to switch to a persistent production deployment
        environment:
            - VIRTUAL_HOST=library.agill.xyz,library.agill.net
            - LETSENCRYPT_HOST=library.agill.xyz,library.agill.net
