[package]
name = "scorarium-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Test fixtures for scorarium"

[dependencies]
axum-test.workspace = true
ctor.workspace = true
scorarium.workspace = true
scorarium-archive.workspace = true
scorarium-client = { workspace = true, features = ["fake-transport"] }
tracing.workspace = true
tracing-subscriber.workspace = true
