[package]
name = "scorarium"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A physical and digital sheet music library"

[dependencies]
clap.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
