[package]
name = "scorarium"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "A physical and digital sheet music library"

[dependencies]
askama.workspace = true
axum.workspace = true
axum-extra.workspace = true
clap.workspace = true
color-eyre.workspace = true
cookie.workspace = true
getrandom.workspace = true
rust-embed.workspace = true
scorarium-archive.workspace = true
serde.workspace = true
serde_html_form.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
axum-test.workspace = true
scorarium-tests.workspace = true
